/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DeleteUsuario200Response from './model/DeleteUsuario200Response';
import DeleteUsuarioRequest from './model/DeleteUsuarioRequest';
import Usuario from './model/Usuario';
import UsuariosApi from './api/UsuariosApi';


/**
* # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | &#x60;/usuario&#x60;   | Obtener todos los usuarios      |  | POST   | &#x60;/usuario&#x60;   | Crear un nuevo usuario          |  | DELETE | &#x60;/usuario&#x60;   | Eliminar un usuario por ID      |    .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDeEmpleados = require('index'); // See note below*.
* var xxxSvc = new ApiDeEmpleados.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDeEmpleados.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDeEmpleados.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDeEmpleados.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DeleteUsuario200Response model constructor.
     * @property {module:model/DeleteUsuario200Response}
     */
    DeleteUsuario200Response,

    /**
     * The DeleteUsuarioRequest model constructor.
     * @property {module:model/DeleteUsuarioRequest}
     */
    DeleteUsuarioRequest,

    /**
     * The Usuario model constructor.
     * @property {module:model/Usuario}
     */
    Usuario,

    /**
    * The UsuariosApi service constructor.
    * @property {module:api/UsuariosApi}
    */
    UsuariosApi
};
