/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteUsuarioRequest model module.
 * @module model/DeleteUsuarioRequest
 * @version 1.0.0
 */
class DeleteUsuarioRequest {
    /**
     * Constructs a new <code>DeleteUsuarioRequest</code>.
     * @alias module:model/DeleteUsuarioRequest
     * @param id {Number} ID del usuario a eliminar
     */
    constructor(id) { 
        
        DeleteUsuarioRequest.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>DeleteUsuarioRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteUsuarioRequest} obj Optional instance to populate.
     * @return {module:model/DeleteUsuarioRequest} The populated <code>DeleteUsuarioRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteUsuarioRequest();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteUsuarioRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteUsuarioRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteUsuarioRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DeleteUsuarioRequest.RequiredProperties = ["id"];

/**
 * ID del usuario a eliminar
 * @member {Number} id
 */
DeleteUsuarioRequest.prototype['id'] = undefined;






export default DeleteUsuarioRequest;

