/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Usuario from './Usuario';

/**
 * The DeleteUsuario200Response model module.
 * @module model/DeleteUsuario200Response
 * @version 1.0.0
 */
class DeleteUsuario200Response {
    /**
     * Constructs a new <code>DeleteUsuario200Response</code>.
     * @alias module:model/DeleteUsuario200Response
     */
    constructor() { 
        
        DeleteUsuario200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteUsuario200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteUsuario200Response} obj Optional instance to populate.
     * @return {module:model/DeleteUsuario200Response} The populated <code>DeleteUsuario200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteUsuario200Response();

            if (data.hasOwnProperty('mensaje')) {
                obj['mensaje'] = ApiClient.convertToType(data['mensaje'], 'String');
            }
            if (data.hasOwnProperty('usuarioEliminado')) {
                obj['usuarioEliminado'] = Usuario.constructFromObject(data['usuarioEliminado']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteUsuario200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteUsuario200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mensaje'] && !(typeof data['mensaje'] === 'string' || data['mensaje'] instanceof String)) {
            throw new Error("Expected the field `mensaje` to be a primitive type in the JSON string but got " + data['mensaje']);
        }
        // validate the optional field `usuarioEliminado`
        if (data['usuarioEliminado']) { // data not null
          Usuario.validateJSON(data['usuarioEliminado']);
        }

        return true;
    }


}



/**
 * @member {String} mensaje
 */
DeleteUsuario200Response.prototype['mensaje'] = undefined;

/**
 * @member {module:model/Usuario} usuarioEliminado
 */
DeleteUsuario200Response.prototype['usuarioEliminado'] = undefined;






export default DeleteUsuario200Response;

