/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Usuario model module.
 * @module model/Usuario
 * @version 1.0.0
 */
class Usuario {
    /**
     * Constructs a new <code>Usuario</code>.
     * @alias module:model/Usuario
     * @param nombre {String} 
     * @param email {String} 
     */
    constructor(nombre, email) { 
        
        Usuario.initialize(this, nombre, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nombre, email) { 
        obj['nombre'] = nombre;
        obj['email'] = email;
        obj['activo'] = true;
    }

    /**
     * Constructs a <code>Usuario</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Usuario} obj Optional instance to populate.
     * @return {module:model/Usuario} The populated <code>Usuario</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Usuario();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('activo')) {
                obj['activo'] = ApiClient.convertToType(data['activo'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Usuario</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Usuario</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Usuario.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

Usuario.RequiredProperties = ["nombre", "email"];

/**
 * @member {Number} id
 */
Usuario.prototype['id'] = undefined;

/**
 * @member {String} nombre
 */
Usuario.prototype['nombre'] = undefined;

/**
 * @member {String} email
 */
Usuario.prototype['email'] = undefined;

/**
 * @member {Boolean} activo
 * @default true
 */
Usuario.prototype['activo'] = true;






export default Usuario;

