/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDeEmpleados);
  }
}(this, function(expect, ApiDeEmpleados) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDeEmpleados.DeleteUsuario200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeleteUsuario200Response', function() {
    it('should create an instance of DeleteUsuario200Response', function() {
      // uncomment below and update the code to test DeleteUsuario200Response
      //var instance = new ApiDeEmpleados.DeleteUsuario200Response();
      //expect(instance).to.be.a(ApiDeEmpleados.DeleteUsuario200Response);
    });

    it('should have the property mensaje (base name: "mensaje")', function() {
      // uncomment below and update the code to test the property mensaje
      //var instance = new ApiDeEmpleados.DeleteUsuario200Response();
      //expect(instance).to.be();
    });

    it('should have the property usuarioEliminado (base name: "usuarioEliminado")', function() {
      // uncomment below and update the code to test the property usuarioEliminado
      //var instance = new ApiDeEmpleados.DeleteUsuario200Response();
      //expect(instance).to.be();
    });

  });

}));
