/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDeEmpleados);
  }
}(this, function(expect, ApiDeEmpleados) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDeEmpleados.UsuariosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsuariosApi', function() {
    describe('createUsuario', function() {
      it('should call createUsuario successfully', function(done) {
        //uncomment below and update the code to test createUsuario
        //instance.createUsuario(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUsuario', function() {
      it('should call deleteUsuario successfully', function(done) {
        //uncomment below and update the code to test deleteUsuario
        //instance.deleteUsuario(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsuarios', function() {
      it('should call getUsuarios successfully', function(done) {
        //uncomment below and update the code to test getUsuarios
        //instance.getUsuarios(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
