/**
 * API de Empleados
 * # API de Gestión de Usuarios 🚀    **Documentación técnica para desarrolladores**      ## 📌 Descripción    API RESTful construida con Node.js y Express para gestionar usuarios. Documentada con Swagger (OpenAPI 3.0) para una integración sencilla y pruebas interactivas.      ## 🔍 Endpoints      | Método | Ruta         | Descripción                     |  |--------|--------------|---------------------------------|  | GET    | `/usuario`   | Obtener todos los usuarios      |  | POST   | `/usuario`   | Crear un nuevo usuario          |  | DELETE | `/usuario`   | Eliminar un usuario por ID      |    
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: equipo@empresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeleteUsuario200Response from '../model/DeleteUsuario200Response';
import DeleteUsuarioRequest from '../model/DeleteUsuarioRequest';
import Usuario from '../model/Usuario';

/**
* Usuarios service.
* @module api/UsuariosApi
* @version 1.0.0
*/
export default class UsuariosApi {

    /**
    * Constructs a new UsuariosApi. 
    * @alias module:api/UsuariosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createUsuario operation.
     * @callback module:api/UsuariosApi~createUsuarioCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Usuario} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Crear nuevo usuario
     * Registra un nuevo usuario en el sistema.
     * @param {module:model/Usuario} usuario 
     * @param {module:api/UsuariosApi~createUsuarioCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Usuario}
     */
    createUsuario(usuario, callback) {
      let postBody = usuario;
      // verify the required parameter 'usuario' is set
      if (usuario === undefined || usuario === null) {
        throw new Error("Missing the required parameter 'usuario' when calling createUsuario");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Usuario;
      return this.apiClient.callApi(
        '/usuario', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUsuario operation.
     * @callback module:api/UsuariosApi~deleteUsuarioCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteUsuario200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Eliminar usuario existente
     * Elimina permanentemente un usuario del sistema. Requiere el ID del usuario en el cuerpo de la solicitud. 
     * @param {module:model/DeleteUsuarioRequest} deleteUsuarioRequest 
     * @param {module:api/UsuariosApi~deleteUsuarioCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteUsuario200Response}
     */
    deleteUsuario(deleteUsuarioRequest, callback) {
      let postBody = deleteUsuarioRequest;
      // verify the required parameter 'deleteUsuarioRequest' is set
      if (deleteUsuarioRequest === undefined || deleteUsuarioRequest === null) {
        throw new Error("Missing the required parameter 'deleteUsuarioRequest' when calling deleteUsuario");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DeleteUsuario200Response;
      return this.apiClient.callApi(
        '/usuario', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsuarios operation.
     * @callback module:api/UsuariosApi~getUsuariosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Usuario>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener todos los usuarios
     * Retorna una lista paginada de todos los usuarios registrados en el sistema. Puede filtrarse por estado activo/inactivo (parámetro opcional). 
     * @param {module:api/UsuariosApi~getUsuariosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Usuario>}
     */
    getUsuarios(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Usuario];
      return this.apiClient.callApi(
        '/usuario', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
